### ISSUE TITLE
Edit Profile

### ISSUE THREAD

**Issue by arbesoft** [Azure-Samples/active-directory-b2c-xamarin-native#116] opened 2020-01-07 01:21 UTC
When I edit my profile, everything is fine, I get right values for example "Username".  If I close the app and start it again and signin, I get the token from cache with my old "Username". Is there a way to fix this?

**Comment by TiagoBrenck** [comment] 2020-01-07 20:02
@arbesoft I could reproduce the bug. It happens if you don't hit "sign-out" and just stop the app from running on Visual Studio. Then when you start it again and press "sign-in", it goes through the acquire token silently code and retrieve an outdated user info.

@bgavrilMS @jennyf19 when I debugged this issue I have noticed that when you sign-in and edit your profile, MSAL cache will have 2 accounts (1 for *sisu* policy and 1 for *edit_profile*). By editing the profile, we update the *id_token* for the *edit_profile* account only, however when you acquire token silently on the sign-in, it looks for the sisu `IAccount`, thus it gets an *id_token* that doesn't have the name updated. Do you have any suggestion on how to deal with this syncing `IAccounts` topic?

**Comment by arbesoft** [comment] 2020-01-07 20:12
@TiagoBrenck  yes it´s right it happens if I don´t  click signout. But I think it´s a real world scenario, if the user close the app,  and if we implement AcquireTokenSilent on start?

**Comment by jennyf19** [comment] 2020-01-08 07:53
@arbesoft This is expected. With AAD B2C, each user flow (policy) is a separate authority, which means a separate account in the cache. That being said, when you target su_si user flow, you get a token in the cache. Then, when targeting the edit profile user flow, you will have a new token in the cache for the edit profile policy. This is why developers using B2C and MSAL are required to do [special cache filtering logic](https://github.com/Azure-Samples/active-directory-b2c-xamarin-native/blob/master/UserDetailsClient/UserDetailsClient.Core/Features/LogOn/B2CAuthenticationService.cs#L128)  if they want to pull a specific AAD B2C token tied to a policy from the cache. This means that, if, after acquiring the edit profile token, you then use the su_si token, it will not have the updated claims in the idToken. Also, AAD B2C does not sync immediately across policies, so in order to see the update in claims in the su_si token when refreshing the access token, one may need to wait a few to several hours. 

cc: @TiagoBrenck 

We know this is not ideal and are working on improving this aspect of our developer experience. However, in the meantime, you can use the filtering by policy or write your own logic to pull out the token for whichever user flow was last applied. This ensures the claims are updated.

**Comment by jennyf19** [comment] 2020-01-22 23:50
@arbesoft closing, as this is by design.

**Closed by jennyf19** 2020-01-22 23:50 UTC
Labels: by design
