### ISSUE TITLE
Issues registering an application in the AAD B2C Portal.

### ISSUE THREAD

**Issue by jakehockey10** [Azure-Samples/active-directory-b2c-xamarin-native#148] opened 2021-02-16 19:55 UTC
Hello,

Thanks for the sample application.  We are having issues getting it to work with our b2c app registration however.  We originally followed several tutorials to get our actual application to use authentication with our b2c app registration.  But after not getting that to work, we moved to trying to get a sample application working.

Here are several tutorials we've followed:
- https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-net-aad-b2c-considerations
- https://www.youtube.com/watch?v=lqfsKtoLHMQ&ab_channel=MattBurrell 
- ... (we've followed more, but probably not necessary to list them all here)

The issue we are running into is that MSAL doesn't think that our app registration was created via the B2C portal.  But we have recreated the app registration over 4 times, all of which are most definitely created in the B2C portal.  We've used the legacy app registration pages as well as the non-legacy app registration pages.  We've tried adding platforms for desktop + mobile as well as the android specific platforms.  We use the default redirect uri each time (`msal<client-id>://auth`).  The most prevalent error message we've gotten is this one:

![image](https://user-images.githubusercontent.com/1821383/108114213-c683f580-7055-11eb-88c4-d6381af4c459.png)

"The provided application with ID <client-id> is not valid against this service.  Please use an application created via the B2C portal and try again."

We've done what the error suggests more than enough times to concede and ask for help.

Another thing we've tried is using existing signup/signin user flows as well as creating dedicated ones for this mobile app specifically.  That doesn't seem to make a difference.

Other variations of the issue have been the browser never showing any web content as opposed to the error message in the screenshot above.  But that was when we had a different app registration created in the exact same way.

We are at a loss with next steps here.  Each tutorial we've tried has different screenshots of what things look like in the B2C portal due to when those tutorials were written, but we've followed each one to a T and keep getting this error or something similar.  Can we get some help pointed in the right direction, please?

**Comment by jennyf19** [comment] 2021-02-18 20:07
@jakehockey10 sorry to hear you're having so many issues w/the app registration. 

to start, 1) can you git clone the [sample](https://github.com/Azure-Samples/active-directory-b2c-xamarin-native) and 2) does it work for you out of the box? it should run as-is without any other user set-up.

Next, you can try creating a b2c test tenant, and then use those values in this same sample. https://docs.microsoft.com/en-us/azure/active-directory-b2c/tutorial-create-tenant

To create a B2C tenant or test tenant, you need an Azure subscription. For example, i'm in my Azure subscription, and then I create a B2C tenant.

![image](https://user-images.githubusercontent.com/19942418/108415016-c6186580-71e1-11eb-9d6a-569d1d935d82.png)

@nickgmicrosoft can you help here as well?

**Comment by jakehockey10** [comment] 2021-02-18 20:57
@jennyf19 Thanks for the response!

I cloned the repo and initially tried it with our b2c setup.  After stashing my changes and running the sample as-is, I do indeed successfully login with the Google provider just fine.

It might take me a while to the point where I can get another Azure subscription going and setup another B2C tenant.  I've been given admin permission to our official one temporarily to get this working, but I don't know if they will give me permission to create another b2c tenant in addition to the one we already have.  So I might have to do this on my personal account.

While I get situated on that front, any ideas what could be going wrong?  From my perspective, I'm just replacing the configuration of the sample's b2c tenant with my work's b2c tenant, and keeping everything else the same.  So that leads me to believe that there is something in our b2c tenant that is blocking/not liking about what we are trying to do here.

I'm helping a colleague figure this out for the xamarin app he's building, but I'm actually working on the web portal that will be showing the data collected in his app in various ways, and that web portal uses the same b2c tenant (different application registration, obviously) successfully for authentication.  So our existing b2c tenant is configured sufficiently for the web portal, and I'm guessing there is some tweaking we need to do to get it to be happy with the desktop/mobile native app registration.

**Comment by jennyf19** [comment] 2021-02-18 21:13
@jakehockey10 These should be all the [steps](https://github.com/Azure-Samples/active-directory-b2c-xamarin-native#optional-step-6-configure-the-visual-studio-project-with-your-app-coordinates) you need to get the sample working w/your own b2c tenant. Basically, you'll replace our configuration w/yours, and yes, it should still work. Android/iOS have some special things to configure, which i believe we have listed in the link above. 

If you run into issues, just give us the specific error you're getting or user experience and we can probably help w/troubleshooting.

**Comment by jakehockey10** [comment] 2021-02-18 21:19
@jennyf19 I'm sorry if I'm misunderstanding.  But we followed these steps several times and the error we get is the one I've shared a screenshot of above.  I'm not sure how to diagnose the issue further than this point.  But after I create a brand new b2c tenant in my personal account and try it with that, I can ping you on here again.

One difference that will be apparent between my personal b2c tenant and our company's is that we are incorporating our company's non b2c AD tenant as an identity provider in addition to the social identity providers.  Our signup/signin user flow seems to be the legacy version as it doesn't look like the user flow UI that this sample gets redirected to, but my understanding is that it should still work with the older user flow.  We did try creating a second signup/signin user flow that is the newer version and still got the same error.

Our b2c tenant is configured to allow our AD tenant as an identity provider as I've said, and then in addition to that, we only allow local accounts beyond that.  We are intentionally not supporting specific social logins like Facebook, Twitter, Google, Github, etc. as this is an enterprise application that we expect our internal employees as well as external clients to use, and we control authorization ourselves based on roles we assign the users after they've successfully signed up to our b2c tenant.

**Comment by jennyf19** [comment] 2021-02-18 21:34
I think @nickgmicrosoft would be the one to help here, but feel free to ping me if your personal b2c tenant doesn't work.

**Comment by jakehockey10** [comment] 2021-03-01 17:06
@nickgmicrosoft Just wanted to make sure you saw this message?

**Comment by jakehockey10** [comment] 2021-03-02 18:39
@jennyf19 any chance we could get someone else to respond?  I'm not convinced @nickgmicrosoft is checking these notifications at all.

**Comment by nickgmicrosoft** [comment] 2021-03-03 18:39
Can you try a few things:
- If you run the user flow from the "run now" experience, do you get the same error? See [here](https://docs.microsoft.com/en-us/azure/active-directory-b2c/tutorial-create-user-flows#test-the-user-flow). Ensure that that the application selected is the one you intend to use:
<img width="1675" alt="runuser" src="https://user-images.githubusercontent.com/58957441/109855055-ab47e700-7c0c-11eb-9f75-28fd602ec008.png">

This will help us localize the issue to something with your app registration/the B2C service or an issue with the MSAL configuration.

**Comment by jakehockey10** [comment] 2021-03-03 19:22
@nickgmicrosoft - For some reason, the application registration is not available in the dropdown when I go to test the user flow.  Other registered applications that I'm the owner of do appear in this dropdown, but the application registration we created for the mobile app will not show up in the dropdown.

Testing the user flow with other application registrations does work.  And we do use this same user flow in an angular application as well as a web api.  So it seems the problem is with the app registration itself.

**Comment by nickgmicrosoft** [comment] 2021-03-03 19:28
Interesting. So it does sound like there is an issue with the app registration. Are you using the Applications or App registrations blade to register the application? Can you use the App registrations blade to create a new app from scratch that's identical to your existing one and see if that shows up in the user flow menu?

If you can send me the app registration manifest, that would be helpful. This file:
![image](https://user-images.githubusercontent.com/58957441/109860957-a175b200-7c13-11eb-9e35-0b6cc9aa3e04.png)

**Comment by jakehockey10** [comment] 2021-03-03 20:14
@nickgmicrosoft Thanks for the response.

We've tried creating app registrations both with the legacy Applications section as well as the newer App App Registrations blade.  Both gave us issues.  However, since we've last looked at this, I see an app registration with a name and configuration that seems like someone else in the company is trying this for the same application (I'm not the owner of it, but it is one that shows up in the dropdown.  The user flow seems to work, but when I change this sample to use this application registration, I get an error where it claims the redirect uri is not set.

Here is the sample code: 
![image](https://user-images.githubusercontent.com/1821383/109865681-93c72900-7c21-11eb-9877-6ec5133be021.png)

I pasted the client id from this application registration into the B2CConstants file.

Here are the redirect uris that someone set on this application registration:
![image](https://user-images.githubusercontent.com/1821383/109865878-dc7ee200-7c21-11eb-8caf-3d5825e26c4f.png)

Debugging the application allows me to confirm that the ClientID from the constants is correct at runtime when making the auth call.

In the browser, the url has an error_description of AADB2C90006%3a+The+redirect+URI+%27msal<our-client-id>%3a%2f%2fauth%27+provided+in+the+request+is+not+registered+for+the+client+id+%27<our-client-id>%27.%0d%0aCorrelation+ID%3a+1ae323f3-5df4-4b91-b36b-3c79e23b5d6d%0d%0aTimestamp%3a+2021-03-03+20%3a12%3a10Z%0d%0a

I will try creating another application registration like I have before to see if I see any different behavior.

**Comment by jakehockey10** [comment] 2021-03-03 20:17
We've also tried different platform settings: 
![image](https://user-images.githubusercontent.com/1821383/109866647-be65b180-7c22-11eb-975f-3e041b9af546.png)
We have tried the Mobile and Desktop Applications platform as well as the Android platform.  Both have given us issues in the past.  But which one would you suggest we use moving forward?

**Comment by jakehockey10** [comment] 2021-03-03 20:22
For now, I chose the Mobile and desktop applications platform and I get directed to the right user flow, and upon completion of the user flow, I never get redirected back to the application in the emulator.  The browser just stays at this url upon the completion of the user flow: https://login.microsoftonline.com/kmsi

**Comment by nickgmicrosoft** [comment] 2021-03-03 22:59
I see. So this is a different issue from the original correct? Still trying to figure out why your original app was throwing the error of 'app can't be found in tenant'. Can you email me the app manifest file for that problematic app to ```edgomezc at microsoft dot com```

**Comment by nickgmicrosoft** [comment] 2021-03-03 23:02
For the "why doesn't it redirect back to my app" - can you try this on a real device? Helps specify whether the issue is due to emulation. Email me some details and we can open a new github issue if that's where you're stuck (since it's diff from thsi thread).

**Comment by jakehockey10** [comment] 2021-03-03 23:40
@nickgmicrosoft yea this seems like different behavior than the original issue, but this is pretty consistent with our findings so far.  Each time we start over with a new application registration, we seem to run into different issues.

I'll email you with the information you've requested, and I'm going to cc my colleague as well so he can keep track of the conversation as well.

**Comment by jakehockey10** [comment] 2021-03-04 18:02
@nickgmicrosoft - I emailed you some more data points on testing with a real mobile phone through usb debugging.  The outcomes are similar to what we see in the emulator.  Looking forward to hearing back from you, and please let me know if there is any other information I can provide

**Comment by nickgmicrosoft** [comment] 2021-03-10 07:38
The issue was that the app registration had the wrong audience, it should be “Accounts in any identity provider or organizational directory (for authenticating users with user flows)”. See [here](https://docs.microsoft.com/en-us/azure/active-directory-b2c/app-registrations-training-guide#new-supported-account-types) for more info. You may have switched to a difference audience type during creation that isn’t compatible with Azure AD B2C user flows.
 
You can’t edit this directly on the portal once you’ve created the app registration (you can see audience by going to the Authentication blade), but you can edit it in the app manifest.
 
In the app manifest, update the **signInAudience** property to be **AzureADandPersonalMicrosoftAccount** instead of **AzureADMyOrg**.

**Comment by nickgmicrosoft** [comment] 2021-03-10 07:40
Closing this issue as the above addressed the "The provided application ID is not valid against this service." For other inquiries/issues, please open new tickets.

**Closed by nickgmicrosoft** 2021-03-10 07:40 UTC
Labels: answered, question
