### ISSUE TITLE
AcquireTokenSilentAsync doesn't work on the iOS emulator

### ISSUE THREAD

**Issue by 7sharp9** [Azure-Samples/active-directory-b2c-xamarin-native#21] opened 2017-07-04 10:11 UTC
Using `AcquireTokenSilentAsync` on the emulator always results in a failure, on an actual device the call succeeds _(Given a previous successful login)_

**Comment by Jeremywhiteley** [comment] 2017-07-18 15:08
Do you know when they are going to fix this or what the work around is?

**Comment by danieldobalian** [comment] 2017-07-19 20:49
@7sharp9 can you turn on MSAL logging and post the logs here? 

My guess is there's some config issue with your iOS emulator that's preventing the tokens from being cache'd.

**Comment by daspuru** [comment] 2017-07-19 20:55
I suspect the issue is in the Keychain storage.

**Comment by wislon** [comment] 2017-07-19 21:20
@daspuru @7sharp9 @Jeremywhiteley it quite likely is related to keychain/shared storage and the entitlements.plist. 

I ran into a similar problem on Android a while back, and put together a small howto/workaround for it over here: http://blog.wislon.io/posts/2016/12/05/msal-token-not-stored-on-android (it basically swaps out the token storage implementation). It worked on the iOS simulator too.

It's not an official workaround by any means, and it may need some tweaking, because it was a few months ago.

I can't find the original link for what to do with the `Entitlements.plist` now, but iirc all you had to do was actually just *have* an `Entitlements.plist` (even if it was empty). But that opened another can of worms in my situation, because suddenly none of the provisioning certs would work any more.

HTH get you going again :)

**Comment by 7sharp9** [comment] 2017-07-20 09:35
@danieldobalian How do you turn on that logging?
@wislon I already have a populated `Entitlements.plist`, Im also using adhock enterprise provisioning, not sure if that makes any difference.

**Comment by wislon** [comment] 2017-07-20 21:37
@7sharp9 in that case, I would think that the provisioning profile wouldn't make a difference. assuming of course it's all related to shared storage/keystore in the first place 😉

**Comment by daspuru** [comment] 2017-07-20 22:18
How about this? 

https://forums.developer.apple.com/thread/60617

It's just an idea as I don't use the simulators.

**Comment by isangines** [comment] 2018-04-04 13:11
@7sharp9  I'm having the same issue, did you find any work around? Thanks!

**Comment by jmprieur** [comment] 2018-04-10 16:51
@jennyf19 do we have an idea of what could happen?

**Comment by jennyf19** [comment] 2018-04-10 18:10
@jmprieur - not sure, I will try to repro this today...I know from another [issue](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues/997) doing this: 
**KeyChain Groups should be enabled at Entitlements.plist** 
solved the problem of an empty cache after authentication with Xamarin iOS. Not sure if it is related to this iOS simulator issue.

**Comment by jennyf19** [comment] 2018-04-28 00:29
Using the sample and iPhone SE 11.3 simulator, I was able to:

> Hit Sign-In (entered username, password)
> Hit Sign-Out
> Hit Sign-In -> Asked to "Pick an Account"
> Picked account and was logged in (not prompted to enter password again)
> Closed the simulator and restarted
> Hit Sign-in -> Asked to "Pick an Account"
> Picked account and was logged in (not prompted to enter password again)

Based on this analysis, the cache with simulator appears to be working as expected. According to iOS team, simulator does not use keychain sharing group, but a device will use keychain.

@7sharp9 Can you please give more details into what you are experiencing with the sign-in flow on the simulator? Thank you.

cc: @jmprieur

**Comment by jennyf19** [comment] 2018-05-01 17:05
@jmprieur @7sharp9  
Based on my testing yesterday, you only need to have an empty entitlement file (I think @wislon mentioned this above)...something like this:
```
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
</dict>
</plist>

If either of you want to try this and let us know the results, it would be much appreciated.

**Comment by jennyf19** [comment] 2018-07-06 05:20
@7sharp9 @Jeremywhiteley @isangines @wislon @daspuru 
This has been addressed and the [readme updated](https://github.com/Azure-Samples/active-directory-b2c-xamarin-native/blob/master/README.md#ios-specific-considerations). Simulator does not use keychain sharing group, but a device will.

Going to close this issue, but feel free to reopen or respond if the issue continues.

cc: @bgavrilMS @jmprieur

**Closed by jennyf19** 2018-07-06 05:20 UTC
