### ISSUE TITLE
Profile edit policy asks users to sign in again although they are already logged in

### ISSUE THREAD

**Issue by BtrJay** [Azure-Samples/active-directory-b2c-xamarin-native#35] opened 2017-11-14 01:00 UTC
Hi all,

I've found this issue when I create a edit profile policy in Azure B2C and replicate the snippets from the sample.

The snippet below is from the sample

// KNOWN ISSUE:
// User will get prompted 
// to pick an IdP again.
AuthenticationResult ar = await App.PCA.AcquireTokenAsync(App.Scopes, GetUserByPolicy(App.PCA.Users, App.PolicyEditProfile), UIBehavior.SelectAccount, string.Empty, null, App.AuthorityEditProfile, App.UiParent);

Are there any updates on this? Or any workarounds to handle profile editing without sign-in again?

Kind Regards,

Jay

**Comment by jennyf19** [comment] 2018-12-20 17:14
@BtrJay @dgonzalezp This was fixed in [MSAL 2.5.0-preview](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/releases/tag/MSAL-v2.5.0). We added `UIBehavior.NoPrompt` so now, when doing edit profile policy, you can elect to not show a UI to the user. B2C server will determine if it's necessary to show a prompt or not. The user experience is much better, as they now go directly to the edit profile page. 
Closing as the issue is resolved. Please reopen or make another if you run into more issues. Thanks!

The B2C xamarin sample is up to date with these changes.

**Closed by jennyf19** 2018-12-20 17:14 UTC
