### ISSUE TITLE
Stays on login screen after user has successfully logs in

### ISSUE THREAD

**Issue by TomWalkerCodes** [Azure-Samples/active-directory-b2c-xamarin-native#15] opened 2017-06-18 17:42 UTC
We are using the latest updates v1.10 within our MVP.  It never leaves the web login view once the user has successfully logged.

**Comment by parakhj** [comment] 2017-06-19 22:18
Which client is this for? Android/iOS/Windows? You may need to fix the redirect URI so that the app is listening to that redirect uri scheme

**Comment by TomWalkerCodes** [comment] 2017-07-14 23:12
Sorry, for the delay in response.   I'm just getting back to this issue.  

Trying to using the updated MSAL library with a Xamarin.Forms.  I'm able to get the MSAL alpha version working with our application.  The leap from alpha version to v1.10 is really hurting alot.  MS team seems to have made the library more complicated to work with.

We have redirect URI which works.   I'm not clear on where I need to add the redirect url  to the configuration for the Xamarin.Forms.  

Right now I'm just using the Xamarin.Forms example in this github repo and attempting to use our existing Azure ADB2C configuration from our application.  So I am replacing the Azure ADB2C in the App.cs file with our own Azure ADB2C.   The ADB2C  settings that worked for the alpha version do not work at all for this version.   So I'm trying to work out is it a setup issue on Azure or am I entering the incorrect values into the parameters.

Right now I need to understand where to pull the configuration values for the following settings for Azure portal.   The docs with the example do not provide enough information to work where the information comes from the Azure portal.

    public static string[] Scopes = { "" };
    public static string ApiEndpoint = "";
    public static string AuthorityBase = $"";

**Comment by parakhj** [comment] 2017-07-24 06:46
Which client is this for? Android/iOS/Windows? I would also encourage providing the library feedback [here](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet), noting down the frustrations you've had since the update.

**Comment by pedramp20** [comment] 2017-10-02 11:34
I have the same issue with the Android client on a Samsung device (API 21) and  get "This site can't be reached", It shows the expected redirect url msal{appid}://auth/?state={very long token} might be temporarily down or it may have move permanently to a new web address. ERR_UNKOWN_URL_SCHEME." on another Samsung device (API 24)

**Comment by jennyf19** [comment] 2019-02-11 21:15
@TomWalkerCodes @pedramp20 Closing, as pertains to an old version of MSAL. MSAL v2+ may or may not reproduce the issue, as we have changed the webview implementation (ex. you can now use embedded webview). Please reopen if necessary. Thank you!

**Closed by jennyf19** 2019-02-11 21:15 UTC
