### ISSUE TITLE
iOS Device username field showing "Missing from the token response"

### ISSUE THREAD

**Issue by markti** [Azure-Samples/active-directory-b2c-xamarin-native#81] opened 2019-04-07 21:54 UTC
I followed the instructions to add the Entitlements.plist as the custom entitlements and got it working but when I did that I started getting a soft error message when navigating to the AzureAD login, the username field was pre-filled with "Missing from the token response". If I remove that text and replace it with a valid username and password the login screen works fine. I'm not sure why this is happening. Maybe some cached data in Safari?

**Comment by jennyf19** [comment] 2019-04-08 21:24
@markti this is a known issue w/B2C. The reason is because B2C does not return a value in the IdToken for preferred username because of the limitations with the social accounts. For example, AAD does return a value here because it knows who the user is, but for b2c, because the user can sign in with a local account, FB, Github, etc...there is not a consistent value for them to use for preferred username. Also, some social accounts (like Github) don't require email. So...to unblock MSAL from rolling out cache compatibility with ADAL, we decided to use "Missing from the token response" on our end when dealing with the B2C accounts.
You can, however, use the "name" claim as the preferred username. I believe you can add that in the policy. If you need more information on this, let me know and I'll sync w/B2C. It's generally mentioned in this [B2C doc](https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-reference-policies#frequently-asked-questions) -> "In the Return claim column, choose claims you want returned in the authorization tokens sent back to your application after a successful profile editing experience. For example, select Display Name, Postal Code.”

closing, as this is by design currently, but please tag me if you need more guidance on this.

**Closed by jennyf19** 2019-04-08 21:24 UTC
Labels: Preferred_username, by design

**Comment by markti** [comment] 2019-04-09 16:49
@jennyf19 if this is a known issue could this and other known issues with B2C be added to the documentation? Better yet, could there be a separate B2C example for Xamarin Forms that makes everything work for B2C only? :)

**Comment by jennyf19** [comment] 2019-04-09 18:32
@markti Where would you like to see this documented? I'll add it to the MSAL wiki for sure. We are in the process of moving the .NET wiki to docs.ms, so that will help with discoverability. Is there another place you think we should include it? 
You should be able to use the email claim as the username. If it doesn't work, let me know and I'll follow up with B2C. Thanks.

**Comment by jennyf19** [comment] 2019-04-10 00:10
@markti Done. Feel free to add more [info](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/AAD-B2C-specifics#preferred_username-missing-from-the-token-response) if you want, especially to the mitigation section. thank you!

**Comment by vardansargsyan92** [comment] 2021-01-28 14:12
Still getting this issue on IOS. WithLoginHint works only for UWP.

**Comment by jennyf19** [comment] 2021-01-28 18:08
@vardansargsyan92 doing something like [this](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1731#issuecomment-658320529) doesn't work for you on iOS?

**Comment by vardansargsyan92** [comment] 2021-01-29 06:42
Hello @jennyf19 

Yes, you are correct. I am using that mechanism, but unfortunately, it does not work for IOS. And the thing that makes me sad, that whenever I search this issue, it says that this is a "Known" issue, but there is no proper workaround for fixing it. I understand that perhaps it is a big deal to fix it, but I think it is not big enough to hide this message from ordinary app users. Imagine that I am an application consumer, and when I try to sign in, I see a message "Missing from the token response." in the username field. I am not a developer, and  I am not familiar with the active directory. I don't even know what the "Token" is and what is the meaning of token. So how that message could be helpful for me?. In no way. Don't you agree that this message should not be in the UI?. So that is why I am using LoginHint to somehow hide it from ordinary consumers, but unfortunately, that works only on UWP (My application targets IOS and UWP).

**Comment by jennyf19** [comment] 2021-01-29 17:27
@vardansargsyan92 it should only show in the UI if you use `.WithAccount()`, as MSAL pulls that account from the cache...agree that it's not ideal, but the workaround is what i posted above. The reasoning for this is also posted there, we have no way of knowing the preferred user name for b2c scenarios. In my previous testing, this was working on iOS and Android. Please open an issue in the [MSAL library](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues) and someone from the team will take a look. This is for tracking purposes. Thank you, and appreciate the feedback, will rely to the right people.

**Comment by vardansargsyan92** [comment] 2021-02-01 07:22
Hello @jennyf19. Thank you a lot for your response. Yes you are correct I am using `.WithAccount()` in the builder and it looks like this 
`AuthenticationResult authResult = await Pca.AcquireTokenInteractive(_authConfig.Scopes)
                                                       .WithAccount(GetAccountByPolicy(accounts, _authConfig.SignInPolicy))
                                                       .WithLoginHint(_settings.LastSignedInUsername)
                                                       .ExecuteAsync()` 

I could get along without using that method, but unfortunately, if I am not passing the WithAccount to the builder, I lose the cashing mechanism. Thus I have to sign in each time when I run the app. So this solution is not desirable for me. Anyway, thank you again for your attention. I appreciate it. I will try to play with the SignInInteractively method passing the WithAccount for only cases when accounts do not have "Missing token key from the response." username and will see if that can help me or not.

**Comment by vardansargsyan92** [comment] 2021-02-01 07:28
Just forgot  to add about the scenario from which I get the "Wrong" username ))

1. Create an account in the Azure portal (Azure AD B2C User) 
2. Run the [sample](https://github.com/Azure-Samples/active-directory-b2c-xamarin-native)
3. Sign In using the "Forget Password" flow
4. Close the app
5. Remove the newly added user from the Azure portal
6. Re-run the app and try to sign in again.

**Comment by jennyf19** [comment] 2021-02-02 01:55
@vardansargsyan92 thanks for all the details. You shouldn't lose any caching for not including .WithAccount in the interactive call. If you're removing the user, then yes, you'll have to sign in again, but if you didn't, the app will work, you'll get sso, especially with system browser. Let me know if you want more help w/this.

**Comment by vardansargsyan92** [comment] 2021-02-02 08:22
Hello @jennyf19. Thank you a lot for your feedback.
