### ISSUE TITLE
Error: We can't connect to the service you need right now. Check your network connection or try this again later

### ISSUE THREAD

**Issue by JPhilC** [Azure-Samples/active-directory-b2c-xamarin-native#28] opened 2017-10-02 19:15 UTC
Hello all,

I have been trying to get this example to work. First Android, then iOS and finally with UWP simply to get better error results. Ideally I would like it working on iOS. I have a B2C client and a web API set up and working. How do I know this? Because I have the "active-directory-b2c-wpf" example working fine.

In the UWP client the application runs when when I click the sign in button a dialog appears with the progress spinner and then after a second or two I get an error message "We can't connect to the service you need right now. Check your network connection or tray again later". If I close this window the client code throws an exception:
```
Microsoft.Identity.Client.MsalException: WAB authentication failed ---> System.IO.FileNotFoundException: The specified protocol is unknown. (Exception from HRESULT: 0x800C000D)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
```

If I compare what is going down the wire from the WPF client and the UWP client when the AcquireTokenAsync method is called they differ.

The WPF client sends the following information (xxxx replaces sensitive info):
```
GET /te/xxxxx.onmicrosoft.com/b2c_1_susi/oauth2/v2.0/authorize?scope=https%3A%2F%2Fxxxxx.onmicrosoft.com%2Fcms%2Faccess+offline_access+openid+profile&response_type=code&client_id=xxxxx&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&client-request-id=fcdb2f65-9ef2-4c0b-af69-cc337d4067d6&x-client-SKU=MSAL.Desktop&x-client-Ver=1.1.0.0&x-client-CPU=x64&x-client-OS=Microsoft+Windows+NT+6.2.9200.0&prompt=select_account&code_challenge=9ErDqtNfDqGU7IFtTVBccVILq49xl_h50xyv8S25cE8&code_challenge_method=S256&state=a006328c-036b-487b-a9e9-0813facaa55a HTTP/1.1
```
The UWP client sends something of the form:
```
GET /tfp/xxxxx.onmicrosoft.com/b2c_1_susi/v2.0/.well-known/openid-configuration HTTP/1.1
```
I have checked and double checked the b2c-xamarin-native code compared to the b2c-wpf and they are identical apart from the call to AcquireTokenAsync.

In WPF it looks like the following:
``` 
 authResult = await App.PublicClientApp.AcquireTokenAsync(
               App.ApiScopes,
               GetUserByPolicy(App.PublicClientApp.Users, App.PolicySignUpSignIn),
               UIBehavior.SelectAccount, string.Empty, null, App.Authority);
```

for UWP it looks like:

```
 AuthenticationResult ar = await App.PCA.AcquireTokenAsync(
                  App.ApiScopes,
                  GetUserByPolicy(App.PCA.Users, App.PolicySignUpSignIn),
                  App.UiParent);
```

Do I need to configure something different on the backend to get mobile/UWP clients working or do I need to look elsewhere?

Any help would be appreciated.

**Comment by josuuribe** [comment] 2017-10-02 19:25
Usually it menas you have a connectivity problem, possible a proxy like fiddler try to deactive them (or firewalls)

**Comment by JPhilC** [comment] 2017-10-02 21:17
Nope, if that was the case the wouldn't WPF client fail? 

Same machine, two sessions of Visual Studio 2017. One with the B2C-wpf solution loaded the other with the B2C-Xamarin-Native solution loaded. Debug B2C-WPF solution with Fiddler running and it works fine. Debug the Xamarin solution and I get the error. 

Shouldn't the PublicClientApp in both solutions be sending the same GET request down the wire?

**Comment by matgutschow** [comment] 2017-10-20 15:05
Ran into this issue as well running the UWP project, after looking at the sample code with the sample tenant and looking at the PCA object I was able to find that the `RedirectUri` property on the `PublicClientApplication` gets overridden from what you put in the `UserDetailsClient\App.cs`.  If you look in the [UserDetailsClient.UWP/MainPage.cs](https://github.com/Azure-Samples/active-directory-b2c-xamarin-native/blob/master/UserDetailsClient/UserDetailsClient.UWP/MainPage.xaml.cs#L26) you will see it gets overridden.  

If you copy that RedirectUri and add that to your B2C application 'Custom Redirect URI' along with the `msal<applicationID>://auth` from the directions and save it it should work.

**Comment by nalthoff** [comment] 2017-11-07 20:02
the answer in @matgutschow worked for me. Thanks!

**Comment by sellingerd** [comment] 2017-12-21 13:13
The answer by @matgutschow  worked for me too.  What I would like to know is where the redirect URI comes from?  Can I get it from the project without having to use the debugger to see the overridden redirect URI?  Thanks!

**Comment by ajaykeshri** [comment] 2018-09-15 04:48
Hi @matgutschow  I changed RedirectUri and add that to your B2C application 'Custom Redirect URI' along with the msal<applicationID>://auth from the directions and save it it should work.
But Still getting same issue. is it required to give internet UWP permission like android ??

**Comment by alessandro-avila** [comment] 2018-10-21 17:49
Hi @ajaykeshri, have you tried to enable **Private Netowkr (Client & Server)** UWP Capability? Had the same issue, I resolved in this way.

**Comment by yschkatula** [comment] 2019-02-01 13:54
@alessandro-avila, bingo! Experienced the same issue on "msgraph-training-uwp" sample, got it resolved with "Private Network" capability manually switched on (it seems, Microsoft has quite relaxed security model in their intranet area so they can run such samples with no error)

**Comment by jennyf19** [comment] 2019-02-11 21:10
@JPhilC @josuuribe @matgutschow @nalthoff @sellingerd @yschkatula @alessandro-avila @ajaykeshri 

For UWP, you need to set the following in the Package.appxmanifest of the UWP app, in the Capabilities tab:
-Enterprise Authentication
-Private Networks (Client & Server)
-Shared User Cert IWA not enabled by default because apps requesting the Enterprise Auth or Shared User Cert capabilities require a higher level of verification

For example:
```CSharp
  <Capabilities>
    <Capability Name="internetClient" />
    <Capability Name="privateNetworkClientServer" />
    <uap:Capability Name="enterpriseAuthentication" />
    <uap:Capability Name="userAccountInformation" />
  </Capabilities>
```
See [here for more details](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/UWP-specifics#properties-of-platformparameter-specific-to-winrt-and-uwp-corporate-network)

**Comment by jennyf19** [comment] 2019-03-28 20:50
@JPhilC @josuuribe @matgutschow @nalthoff @alessandro-avila  @yschkatula @ajaykeshri Going to close, but please reopen if needed. Thanks.

**Closed by jennyf19** 2019-03-28 20:50 UTC

**Comment by n8allan** [comment] 2019-11-19 17:05
Not sure why this was closed when this remains a genuine problem with the ad b2c sample. 
 .WithRedirectUri() should be added to the sample (when creating the AuthenticationClient) and associated documentation.  Without this, the sample doesn't work and unless someone stumbles on this issue, they'll be hopelessly stuck (I was for hours).

**Comment by jennyf19** [comment] 2019-11-19 21:39
@n8allan not sure what the issue is that you had. We do have `.WithRedirectUri()` in the sample [here](https://github.com/Azure-Samples/active-directory-b2c-xamarin-native/blob/master/UserDetailsClient/UserDetailsClient.Core/Features/LogOn/B2CAuthenticationService.cs#L23)...we test this sample with each release of MSAL to ensure it is working. Would like to know more about the issue you were running into. Thanks.

**Comment by n8allan** [comment] 2019-11-21 16:48
I wish I had seen that sample instead.  [This](https://github.com/xamarin/xamarin-forms-samples/blob/master/WebServices/AzureADB2CAuth/ADB2CAuthorization/App.xaml.cs#L19) is the one I was referring to and as you can see it doesn't have that critical line.

**Comment by jennyf19** [comment] 2019-11-21 17:03
@n8allan oh...i see. Thank you. We (MSAL .NET team) do not own that sample. Sorry lost time on it. We will sync w/the sample owners and update.
cc: @jmprieur - I'll submit a PR to update their sample.

**Comment by jennyf19** [comment] 2019-12-04 17:01
@n8allan the sample has been fixed

**Comment by n8allan** [comment] 2019-12-05 18:09
Thank you @jennyf19 .

**Comment by HappyNomad** [comment] 2020-12-08 16:22
> Also, @n8allan did you get any error messages or anything from MSAL? We have responses that should guide you to fixing issues like this, but if you were stuck for hours, then obviously we do not. Any suggestions you have to help make this more actionable for customers are much appreciated.

I was stuck for hours, too, since all I got was the error in the UI mentioned above and this cryptic exception:

> System.IO.FileNotFoundException: 'The specified protocol is unknown. (Exception from HRESULT: 0x800C000D)'

A more actionable exception message would have been nice.

**Comment by HappyNomad** [comment] 2020-12-08 16:22
@jennyf19

**Comment by jennyf19** [comment] 2020-12-08 19:32
@HappyNomad thanks for tagging me. do you have a repro you can provide that shows the error you mention (`System.IO.FileNotFoundException: 'The specified protocol is unknown. (Exception from HRESULT: 0x800C000D)`) ? Then I can figure out where to put a better error message. Also, would you mind opening an issue in [MSAL .NET](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/new/choose) for this? thank you.

**Comment by sgnanajothi** [comment] 2022-05-22 09:44
> Ran into this issue as well running the UWP project, after looking at the sample code with the sample tenant and looking at the PCA object I was able to find that the `RedirectUri` property on the `PublicClientApplication` gets overridden from what you put in the `UserDetailsClient\App.cs`. If you look in the [UserDetailsClient.UWP/MainPage.cs](https://github.com/Azure-Samples/active-directory-b2c-xamarin-native/blob/master/UserDetailsClient/UserDetailsClient.UWP/MainPage.xaml.cs#L26) you will see it gets overridden.
> 
> If you copy that RedirectUri and add that to your B2C application 'Custom Redirect URI' along with the `msal<applicationID>://auth` from the directions and save it it should work.

**Comment by sgnanajothi** [comment] 2022-05-22 09:47
> Ran into this issue as well running the UWP project, after looking at the sample code with the sample tenant and looking at the PCA object I was able to find that the `RedirectUri` property on the `PublicClientApplication` gets overridden from what you put in the `UserDetailsClient\App.cs`. If you look in the [UserDetailsClient.UWP/MainPage.cs](https://github.com/Azure-Samples/active-directory-b2c-xamarin-native/blob/master/UserDetailsClient/UserDetailsClient.UWP/MainPage.xaml.cs#L26) you will see it gets overridden.
> 
> If you copy that RedirectUri and add that to your B2C application 'Custom Redirect URI' along with the `msal<applicationID>://auth` from the directions and save it it should work.

Hi @matgutschow ...I am new to this azure directory login.... I saw your comments above. What should I need to do to resolve this issue??? Please help....login is happening by enabling the proxy/fiddler

**Comment by sgnanajothi** [comment] 2022-05-22 09:48
I m developing xamarin forms UWP application.... should I need to do any change in code
