### ISSUE TITLE
application does not have keychain access groups enabled in the entitlements.plist

### ISSUE THREAD

**Issue by markti** [Azure-Samples/active-directory-b2c-xamarin-native#84] opened 2019-05-02 21:51 UTC
I am so frustrated. This thing is so brittle it is driving me insane.

Forget about getting this to work in my actual Xamarin app. I'm just trying to get this to work in the code I cloned from this repo! Can't do that consistently.

I am trying to run in the simulator. The login browser screen comes up (amazingly) I login (apparently successfully). Then I get hit with an exception "Microsoft.Identity.Client.MsalClientException: the application does not have keychain access groups enabled in the Entitlements.plist. The keychain access group 'com.yourcompany.UserDetailsClient' is not enabled in Entitlements.plist.".

The app came with the following keychain access enabled item: "com.microsoft.adalcache". This codebase the application has the "Bundle Identifier" of "com.yourcompany.UserDetailsClient". So according to this error message i simply need to add the Bundle Identifier "com.yourcompany.UserDetailsClient" to the Entitlements.plist and it should work, right?

It doesn't.

**Comment by jennyf19** [comment] 2019-05-03 21:48
@markti - glad you didn't give up on us before your huge PR :) 
Adding the .WithIosKeychainSecurityGroup() resolved the issue, correct? if so, looks like the error message needs to be more actionable.

**Comment by jennyf19** [comment] 2019-06-03 23:00
closing as resolved

**Closed by jennyf19** 2019-06-03 23:00 UTC

**Comment by keerthinathganjam** [comment] 2020-12-07 09:19
Getting the same error how to solve this? i an simply trying to run the sample app. Any Changes i need to make this work?

**Comment by jennyf19** [comment] 2020-12-09 02:35
@keerthinathganjam you might want to check out this [documentation](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-net-xamarin-ios-considerations). specifically this [section](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-net-xamarin-ios-considerations#enable-keychain-access) on the keychain.

**Comment by keerthinathganjam** [comment] 2020-12-09 09:16
@jennyf19 I have follwed all the steps specified inthe document, but still getting the same error. Is there anything i need to do in the apple developer portal side?

**Comment by jennyf19** [comment] 2020-12-09 17:28
@keerthinathganjam  you need to have an apple developer account, make sure everything is signed in correctly w/Visual Studio and XCode. Also, you might have to manually add the entitlements.plist - like shown [here](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/783#issuecomment-565616599)

**Comment by keerthinathganjam** [comment] 2020-12-10 08:37
![image](https://user-images.githubusercontent.com/12542938/101742372-7b4ae500-3af0-11eb-89e2-92f47f72b9cb.png)

Here is the screen shot of my visual studio xamarine project ios settings

![MicrosoftTeams-image (6)](https://user-images.githubusercontent.com/12542938/101743307-b2b99180-3af0-11eb-998f-dcf09dc65b6e.png)

Here is the error i am getting.

**Comment by jennyf19** [comment] 2020-12-10 12:18
@keerthinathganjam b2c is not supported with the broker. Have you tried without?

**Comment by keerthinathganjam** [comment] 2020-12-10 14:35
@jennyf19 : I am not using B2C, its normal Azure AD Account only, where i am trying. I am able to work the same sample for Android , it works like a charm, I am able to login and get the Single signon work and in the azure as signin logs device id is also filled. The problem is only with IOS App Sinerio

**Comment by jennyf19** [comment] 2020-12-10 16:31
@keerthinathganjam I see. this is a b2c sample, which is why i was confused. we have a [xamarin aad sample](https://github.com/Azure-Samples/active-directory-xamarin-native-v2/tree/master/2-With-broker/UserDetailsClient/UserDetailsClient.iOS), which uses broker, if you want to try that and see if it works. it's pretty tricky to get iOS up and working.

**Comment by keerthinathganjam** [comment] 2020-12-11 05:45
@jennyf19 : Actually i am trying the sample which you have sent only may be il log an innsue under that repository.

**Comment by jennyf19** [comment] 2020-12-11 17:06
@keerthinathganjam yes, let's log an issue over there, if you don't mind, and please tag me so i get a notification. thank you.

**Comment by jennyf19** [comment] 2020-12-11 17:50
https://github.com/Azure-Samples/active-directory-xamarin-native-v2/issues/157

**Comment by stanleywailers** [comment] 2021-01-21 15:04
I am getting the same error when upload and test the IPA on AppCenter

![Captura de Pantalla 2021-01-21 a la(s) 09 03 29](https://user-images.githubusercontent.com/43071550/105368886-99b00000-5bc7-11eb-9e6c-b270528b3a3f.png)

This is my debug config

![Captura de Pantalla 2021-01-21 a la(s) 09 04 19](https://user-images.githubusercontent.com/43071550/105368984-b2b8b100-5bc7-11eb-97ba-564954ac9a23.png)
