### ISSUE TITLE
Android project won't redirect back to app

### ISSUE THREAD

**Issue by kcorrea96** [Azure-Samples/active-directory-b2c-xamarin-native#47] opened 2018-03-21 23:58 UTC
I'm a bit new to Azure & Xamarin.Forms and am trying to build a simple login application. I've gone through this tutorial multiple times and can't help but feel like I'm missing something. My application successfully brings me to the login page & allows me to enter my credentials, but when I click login it brings me to a blank screen (as seen below).

<img width="401" alt="screen shot 2018-03-21 at 7 50 26 pm" src="https://user-images.githubusercontent.com/25405448/37743586-2caac1aa-2d41-11e8-9946-d34ac2a14adc.png">

My android manifest looks like:

`<uses-sdk android:minSdkVersion="25" />
	<uses-permission android:name="android.permission.INTERNET" />
	<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
	<application>
		<activity android:name="microsoft.identity.client.BrowserTabActivity">
			<intent-filter>
				<action android:name="android.intent.action.VIEW" />
				<category android:name="android.intent.category.DEFAULT" />
				<category android:name="android.intent.category.BROWSABLE" />
				<data android:scheme="msal{app-id-of-native-aad-application}" android:host="auth" />
			</intent-filter>
		</activity>
	</application>
</manifest>`

The redirect URI of my native app is set to msal{app-id-of-native-aad-application}://auth and the reply URI of my api (though from what i've seen this doesn't really matter) is set to https://localhost:44316/

I've changed the variables in the PCL as follows:

```
public static readonly string Tenant = "qalog.onmicrosoft.com"; // Domain/resource name from AD B2C
        public static readonly string ClientID = "{app-id-of-native-aad-application}"; // Application ID from AD B2C
        public static string PolicySignUpSignIn = "B2C_1_LoginApp"; // Policy name from AD B2C
        public static string PolicyEditProfile = "B2C_1_EditProf";
        public static string PolicyResetPassword = "B2C_1_ResetPass";

        public static readonly string[] Scopes = { "https://qalog.onmicrosoft.com/api/read", "https://qalog.onmicrosoft.com/api/user_impersonation"}; // Leave blank unless additional scopes have been added to AD B2C
        public static string ApiEndpoint = "https://fabrikamb2chello.azurewebsites.net/hello";

        public static string AuthorityBase = $"https://login.microsoftonline.com/tfp/{Tenant}/"; // Doesn't require editing
        public static string Authority = $"{AuthorityBase}{PolicySignUpSignIn}"; // Doesn't require editing

```
Am I missing something/does anyone have suggestions?

**Comment by jennyf19** [comment] 2018-05-01 16:55
@kcorrea96 were you able to get the sample running as-in, without changing any of the properties?

**Comment by jennyf19** [comment] 2018-07-12 03:50
@Livven @kcorrea96 Right now, MSAL has to have Chrome or Chrome custom tabs installed on the device in order to show the UI. We have [embedded webview](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Webviews) support coming, and you can try it out [here](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/tree/dev/msal) and give us feedback and suggestions.

**Comment by jennyf19** [comment] 2018-09-16 19:07
Any update on this @Livven @kcorrea96 ? 

We now have the option for [embedded webview](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/MSAL.NET-uses-web-browser#by-default-msalnet-supports-a-system-web-browser-on-xamarinios-and-xamarinandroid) in MSAL (which does not require custom tabs)...please check out the [MSALv2.0.1-preview release](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/releases/tag/MSAL-V2.0.1).


We would love your feedback as well. You can reach me directly or open an issue on the [MSAL repo](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues). 
Thanks!

**Comment by Livven** [comment] 2018-09-17 09:03
@jennyf19 Thanks for the follow-up! Think it should solve https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/589 as well too. I'll let you know if it works out.

**Comment by raasmasood** [comment] 2018-11-18 06:47
just pass true in UIParent that tells android to use embedded browser. 

`  App.UiParent = new UIParent(this, true);`

**Comment by jennyf19** [comment] 2018-12-20 17:10
@kcorrea96 @Livven @raasmasood Closing as the issue is resolved.Thank you

**Closed by jennyf19** 2018-12-20 17:10 UTC
