### ISSUE TITLE
Workflow on iOS not working correctly

### ISSUE THREAD

**Issue by DominicBurford** [Azure-Samples/active-directory-b2c-xamarin-native#74] opened 2019-01-25 14:50 UTC
We have implemented our login to use Azure AD B2C as per this example. It works perfectly fine with Android but we're having some weird issues with iOS (I raised a different but related issue just before Xmas).

Here is the flow on the iOS version of the app.

1. User launches the app and is presented with the Azure AD B2C login screen (correct)
2. User enters their credentials (correct)
3. The app redirects the user back to the login screen (with the username and password fields blank) (wrong)
4. After a few seconds the app then logs them in and navigates them to the main screen

After entering their credentials the user should be immediately navigated to the app main screen, NOT back to the login screen. Once they are logged in, subsequently launching the app correctly logs them in. The problem is only on first login.

After some investigation it seems that this method may be causing the issue.

```
public override bool OpenUrl(UIApplication app, NSUrl url, NSDictionary options)
{
  AuthenticationContinuationHelper.SetAuthenticationContinuationEventArgs(url);
  return true;
}
```
According to the docs

> this logic is meant to ensure that once the interactive portion of the authentication flow is concluded, the flow goes back to MSAL

But it doesn't. It redirects the user back to the _OnAppearing_() method of the login page where it attempts (again) to acquire a token (which it does).

Is there any way to fix the behaviour of this method?

**Comment by jennyf19** [comment] 2019-02-11 20:31
@DominicBurford I finally had time to take a look at this today. I was unable to run the code you sent locally (missing some nuget packages), but it was helpful to look at. I think the issue is with using the `OnAppearing()` method. Every time the app appears, it's going to check the cache and attempt a silent call. You might notice in the sample, we've removed the `OnAppearing()` method logic, as it was causing issues, especially on iOS (which I think you've run into as well).

When I was testing a few months back, I noticed the following when using acquire token logic in `OnAppearing()` :
1. Start app and AT silent is called (and fails because no account yet) 
2. Get sign-in page and login
3. AT silent is called again
4. App continues with the interactive call

Expected:
1. AT silent
2. Catch the `MsalUiRequiredException`
3. Do AT interactive
4. Get back tokens

I could only repro this strange behavior on iOS, so it seems similar to what you are running into. 

**Possible Solution:** remove the sign-in logic from the `OnAppearing()` in your app.

**Comment by DominicBurford** [comment] 2019-02-12 09:15
Looking at the current code in the repo, there is indeed no code in the `OnAppearing`(). I can't see any calls to `AcquireTokenSilentAsync`() so how does the app silently acquire a token if they have previously logged-in? 

Once the user has logged into the app, they should be automatically logged-in on subsequent launches of the app. Is this still possible if we move code out of `OnAppearing`?

**Comment by jennyf19** [comment] 2019-02-12 16:37
@DominicBurford The [silent call](https://github.com/Azure-Samples/active-directory-b2c-xamarin-native/blob/master/UserDetailsClient/UserDetailsClient.Core/MainPage.xaml.cs#L94) is happening in `OnCallApi()`. You could move the OnAppearing() logic to the initialization logic, after InitializeComponent(). Then you could check to see if you have a token in the cache and do the silent flow there, and the call would only happen on initialization instead of onappearing.

We were considering doing this for the sample, but I have not had time to make the update. I might be able to get to in a week, if you can wait that long, or you can try it out and let me know how it goes, but definitely something we should update here.

**Comment by DominicBurford** [comment] 2019-02-12 17:11
@jennyf19 So it is, I didn't spot that. I'll have a look at refactoring the code so as to move the silent call out of the `OnAppearing `method. Thanks for the update on this.

**Comment by jennyf19** [comment] 2019-02-12 18:13
@DominicBurford awesome...let me know how it goes and if this fixes your initial issue.

**Comment by DominicBurford** [comment] 2019-02-13 16:23
After the sugesiton by @jennyf19  I have refactored our code as follows.

- The app attempts to acquire a token silently in the app `OnStart`() in App.xaml.cs 
- If successful the user is navigated to the **_Login_** page (but only to immediately pass-through to the **_MainPage_**)
- If unsuccessful the user is navigated to the **_Login_** page where they need to enter their credentials. If successful they are navigated to the **_MainPage_**.

I have tested this on iOS and Android and all seems to work perfectly. 

Many thanks to @jennyf19 for the suggestion and helping me fix this issue 👍

**Comment by jennyf19** [comment] 2019-02-13 16:42
@DominicBurford Thanks for the details. I will update the sample to reflect a similar change. Glad it's working! 😸

**Comment by jennyf19** [comment] 2019-02-20 02:02
@DominicBurford closing as resolved.

**Closed by jennyf19** 2019-02-20 02:02 UTC
